language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rickymartins/docker-react-training -f Dockerfile.dev .

script:
  - docker run -e CI=true rickymartins/docker-react-training npm run test