version: '3'
services: 
    web:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes: 
            - /frontend
            - ./node_modules:/frontend/node_modules
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /frontend
            - ./node_modules:/frontend/node_modules
        command: ['npm', 'start', 'tests']